services:
  rag-app:
    build: .
    image: yovelz/aws_webapp-rag-app:${APP_VERSION}
    container_name: rag_app
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
      - ./database:/app/database
    command: gunicorn -b 0.0.0.0:5000 --worker-class gthread --workers 2 --threads 4 --timeout 180 app:app
    restart: unless-stopped